# Autogenerated by nbdev

d = { 'settings': { 'branch': 'main',
                'doc_baseurl': '/nbdev-plotly',
                'doc_host': 'https://sudhanshu2340.github.io',
                'git_url': 'https://github.com/sudhanshu2340/nbdev-plotly',
                'lib_path': 'nbdev_plotly'},
  'syms': { 'nbdev_plotly.plotly': { 'nbdev_plotly.plotly.PlotlyProc': ('plotly.html#plotlyproc', 'nbdev_plotly/plotly.py'),
                                     'nbdev_plotly.plotly.PlotlyProc.cell': ('plotly.html#plotlyproc.cell', 'nbdev_plotly/plotly.py'),
                                     'nbdev_plotly.plotly.get_custom_code': ('plotly.html#get_custom_code', 'nbdev_plotly/plotly.py')}}}
