# AUTOGENERATED! DO NOT EDIT! File to edit: ../nbs/00_plotly.ipynb.

# %% auto 0
__all__ = ['PLOTLY_KEY', 'JUPYTER_WIDGET_KEY', 'PlotlyProc']

# %% ../nbs/00_plotly.ipynb 2
from nbdev.process import NBProcessor, dict2nb
from nbdev.process import Processor


# %% ../nbs/00_plotly.ipynb 3
PLOTLY_KEY = 'application/vnd.plotly.v1+json'
JUPYTER_WIDGET_KEY = 'application/vnd.jupyter.widget-view+json'

# %% ../nbs/00_plotly.ipynb 4
class PlotlyProc(Processor):
    "A processor that will do the conversion for outputs"
    has_multiple_cells = False
    def cell(self, cell):
        if 'outputs' in cell:
            output = cell['outputs']
            for k in output:
                if 'data' in k:
                    data = k['data']
                    if PLOTLY_KEY in data:
                        data[JUPYTER_WIDGET_KEY] = data[PLOTLY_KEY]                        
                        del data[PLOTLY_KEY]   
                        print('Plotly replaced')
